### ISSUE TITLE
Definition List causes DOM Exception in markdown to dita conversion

### ISSUE THREAD

**Issue by mblawrence** [jelovirt/org.lwdita#14]
I added a definition list to my document and immediately encountered an DOM exception about inserting a node where it is not permitted.  Removing the definition list allow the app to succeed. 

Here is the problematic document:

~~~
# My Title

This is a sample page

Apple
:   Pomaceous fruit of plants of the genus Malus in
    the family Rosaceae.

Hello there. 

## My Section 

> Long quote
~~~

Running this through lwdita using a java driver produces the following exception:

~~~
Error on line 182 column 3 of specialize.xsl:
  org.w3c.dom.DOMException: HIERARCHY_REQUEST_ERR: An attempt was made to insert a node
  where it is not permitted. 
  at xsl:apply-templates (classpath:///specialize.xsl#182)
     processing /topic/title[1]
  at xsl:apply-templates (classpath:///specialize.xsl#30)
     processing /topic
  at xsl:apply-templates (classpath:///specialize.xsl#11)
     processing /topic
org.xml.sax.SAXException: org.w3c.dom.DOMException: HIERARCHY_REQUEST_ERR: An attempt was made to insert a node where it is not permitted. 
net.sf.saxon.trans.XPathException: org.w3c.dom.DOMException: HIERARCHY_REQUEST_ERR: An attempt was made to insert a node where it is not permitted. 
java.lang.RuntimeException: org.xml.sax.SAXException: org.w3c.dom.DOMException: HIERARCHY_REQUEST_ERR: An attempt was made to insert a node where it is not permitted. 
net.sf.saxon.trans.XPathException: org.w3c.dom.DOMException: HIERARCHY_REQUEST_ERR: An attempt was made to insert a node where it is not permitted. 
	at com.elovirta.dita.markdown.DitaRenderer$MainNodeRenderer.render(DitaRenderer.java:394)
	at com.elovirta.dita.markdown.DitaRenderer.render(DitaRenderer.java:150)
	at com.elovirta.dita.markdown.MarkdownReader.parseAST(MarkdownReader.java:273)
	at com.elovirta.dita.markdown.MarkdownReader.parse(MarkdownReader.java:184)
	at net.sf.saxon.event.Sender.sendSAXSource(Sender.java:427)
	at net.sf.saxon.event.Sender.send(Sender.java:138)
	at net.sf.saxon.jaxp.IdentityTransformer.transform(IdentityTransformer.java:374)
	at com.elovirta.dita.markdown.Driver.main(Driver.java:57)
Caused by: org.xml.sax.SAXException: org.w3c.dom.DOMException: HIERARCHY_REQUEST_ERR: An attempt was made to insert a node where it is not permitted. 
net.sf.saxon.trans.XPathException: org.w3c.dom.DOMException: HIERARCHY_REQUEST_ERR: An attempt was made to insert a node where it is not permitted. 
	at net.sf.saxon.jaxp.TransformerHandlerImpl.endDocument(TransformerHandlerImpl.java:174)
	at com.elovirta.dita.markdown.DitaRenderer$MainNodeRenderer.render(DitaRenderer.java:392)
	... 7 more
Caused by: net.sf.saxon.trans.XPathException: org.w3c.dom.DOMException: HIERARCHY_REQUEST_ERR: An attempt was made to insert a node where it is not permitted. 
	at net.sf.saxon.dom.DOMWriter.startElement(DOMWriter.java:142)
	at net.sf.saxon.event.TreeReceiver.startElement(TreeReceiver.java:180)
	at net.sf.saxon.event.ReceivingContentHandler.startElement(ReceivingContentHandler.java:310)
	at net.sf.saxon.event.ContentHandlerProxy.startContent(ContentHandlerProxy.java:388)
	at net.sf.saxon.event.NamespaceReducer.startContent(NamespaceReducer.java:213)
	at net.sf.saxon.event.ComplexContentOutputter.startContent(ComplexContentOutputter.java:719)
	at net.sf.saxon.event.ComplexContentOutputter.startElement(ComplexContentOutputter.java:294)
	at net.sf.saxon.expr.instruct.ElementCreator.processLeavingTail(ElementCreator.java:330)
	at net.sf.saxon.expr.instruct.Copy.processLeavingTail(Copy.java:415)
	at net.sf.saxon.expr.instruct.TemplateRule.applyLeavingTail(TemplateRule.java:347)
	at net.sf.saxon.trans.Mode.applyTemplates(Mode.java:502)
	at net.sf.saxon.expr.instruct.ApplyTemplates.apply(ApplyTemplates.java:295)
	at net.sf.saxon.expr.instruct.ApplyTemplates.process(ApplyTemplates.java:248)
	at net.sf.saxon.expr.instruct.ElementCreator.processLeavingTail(ElementCreator.java:337)
	at net.sf.saxon.expr.instruct.Copy.processLeavingTail(Copy.java:415)
	at net.sf.saxon.expr.instruct.TemplateRule.applyLeavingTail(TemplateRule.java:347)
	at net.sf.saxon.trans.Mode.applyTemplates(Mode.java:502)
	at net.sf.saxon.expr.instruct.ApplyTemplates$ApplyTemplatesPackage.processLeavingTail(ApplyTemplates.java:553)
	at net.sf.saxon.Controller.transformDocument(Controller.java:2404)
	at net.sf.saxon.Controller.transform(Controller.java:1970)
	at net.sf.saxon.s9api.XsltTransformer.transform(XsltTransformer.java:596)
	at net.sf.saxon.jaxp.TransformerImpl.transform(TransformerImpl.java:73)
	at net.sf.saxon.jaxp.TransformerHandlerImpl.endDocument(TransformerHandlerImpl.java:172)
	... 8 more
Caused by: org.w3c.dom.DOMException: HIERARCHY_REQUEST_ERR: An attempt was made to insert a node where it is not permitted. 
	at org.apache.xerces.dom.CoreDocumentImpl.insertBefore(Unknown Source)
	at org.apache.xerces.dom.NodeImpl.appendChild(Unknown Source)
	at net.sf.saxon.dom.DOMWriter.startElement(DOMWriter.java:138)
	... 30 more
~~~

The source of the driver java application is:

```java

            DocumentBuilderFactory builderFactory = DocumentBuilderFactory.newInstance();
            builderFactory.setNamespaceAware(true);
            DocumentBuilder db = builderFactory.newDocumentBuilder();
            File testfile = new File("sample.md");
            File result = new File("sample.dita");

            Document act;
            InputStream in = new FileInputStream(testfile);
            OutputStream out = new FileOutputStream(result);
            act = db.newDocument();
            Transformer t = TransformerFactory.newInstance().newTransformer();
            XMLReader r = new MarkdownReader();
            InputSource i = new InputSource(in);
            DOMResult res = new DOMResult(act);
            SAXSource intermediate = new SAXSource(r,i);
            t.transform(new SAXSource(r, i), new DOMResult(act));
            TransformerFactory.newInstance().newTransformer().transform(new DOMSource(act), new StreamResult(out));
        } catch (Exception e) {
            System.err.println(e.getMessage());
            e.printStackTrace();
        }
```

**Comment by mblawrence** [comment]
Well, I believe it does, but comes across as:
[topic-fragment] Processing file:/Users/mbl/tmp/tmp/sample.md
[topic-fragment] Error on line 2 column 153 of sample.md:
[topic-fragment]   SXXP0003: Error reported by XML parser: The markup in the document following the root
[topic-fragment]   element must be well-formed.
[topic-fragment] Failed to process XML filter: Failed to transform /Users/mbl/tmp/tmp/sample.md: org.xml.sax.SAXParseException; systemId: file:/Users/mbl/tmp/tmp/sample.md; lineNumber: 2; columnNumber: 153; The markup in the document following the root element must be well-formed.

At least that's what was happening when I was using the dita-ot.  I then took the document and ran it through the driver/test app, isolating the problem in lwdita.
