### ISSUE TITLE
Markdown to DITA failed with Saxon 10 

### ISSUE THREAD

**Issue by DunaMariusCosmin** [jelovirt/org.lwdita#88]
I converted the following Markdown with Saxon 10:
```md
# Title

First \<b>line\</b> text.

Second \</b>\<i>line\</i> text.
```

The conversion broke with the following error:
```
java.util.EmptyStackException: null
	at java.base/java.util.Stack.peek(Stack.java:101)
	at java.base/java.util.Stack.pop(Stack.java:83)
	at net.sf.saxon.tree.tiny.TinyBuilder.endElement(TinyBuilder.java:372)
	at net.sf.saxon.event.Stripper.endElement(Stripper.java:178)
	at net.sf.saxon.event.ReceivingContentHandler.endElement(ReceivingContentHandler.java:607)
	at com.elovirta.dita.markdown.DitaWriter.endElement(DitaWriter.java:182)
	at com.elovirta.dita.markdown.DitaWriter.endElement(DitaWriter.java:172)
	at com.elovirta.dita.markdown.DitaWriter.close(DitaWriter.java:207)
	at com.elovirta.dita.markdown.DitaRenderer$MainNodeRenderer.render(DitaRenderer.java:417)
	at com.elovirta.dita.markdown.DitaRenderer.render(DitaRenderer.java:156)
	at com.elovirta.dita.markdown.MarkdownReader.parseAST(MarkdownReader.java:291)
	at com.elovirta.dita.markdown.MarkdownReader.parse(MarkdownReader.java:210)
	at java.xml/org.xml.sax.helpers.XMLFilterImpl.parse(XMLFilterImpl.java:345)
	at net.sf.saxon.event.Sender.sendSAXSource(Sender.java:439)
	at net.sf.saxon.event.Sender.send(Sender.java:142)
	at net.sf.saxon.Controller.makeSourceTree(Controller.java:1301)
	at net.sf.saxon.s9api.XsltTransformer.transform(XsltTransformer.java:335)
	at net.sf.saxon.jaxp.TransformerImpl.transform(TransformerImpl.java:74)
```

If I catch the `EmptyStackException` into the `DitaWriter.endElement()` method the conversion works like in the previous Saxon versions.

**Comment by jelovirt** [comment]
Can't reproduce with 3.2 and Saxon 10.6
